name: ci
on:
  push:
    branches:
      - master
jobs:
  test:
    name: lint
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '12' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint:ts
      - run: npm run lint:scss
      - run: npm run test
      - run: npm run build
